### ISSUE TITLE
Doesn't work on Linux

### ISSUE THREAD

**Issue by 5HT2** [RubbaBoy/BetterMouse#1]
```
usr@usr-kdeneon:~/Downloads$ java -jar BetterMouse-1.0.0.jar "Downloads"
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/uddernetworks/bettermouse/BetterMouse has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

**Comment by RubbaBoy** [comment]
The reason it isn't working isn't that you're on Linux, it's because you're using an outdated Java. However the program, unfortunately, does not support Linux anyway due to it relying on native Windows APIs. Support isn't planned, as it would require remaking the program entirely.
